### ISSUE TITLE
Link to sensor used

### ISSUE THREAD

**Issue by DaveDavenport** [pvachon/donthuff#1]
Sorry for making this an issue. Please don't shoot :smile: .

What is the logger you use for this? Do you have a alie link or searchable product code?

**Comment by pvachon** [comment]
Ahh, good call -- https://www.aliexpress.com/item/Data-export-S8-M5S-CO2-Sensor-Formaldehyde-PM2-5-detector-PM2-5-dust-haze-Laser-sensor/32792713734.html is the sensor in particular.

**Comment by DaveDavenport** [comment]
Thanks!
